# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radarID', models.CharField(max_length=6)),
                ('location', models.CharField(max_length=50)),
                ('range', models.IntegerField()),
                ('refresh_rate', models.IntegerField()),
            ],
        ),
    ]
